bash: Move script_exit() before it is used
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/wutconv.sh.in b/src/prg/bash/wutconv.sh.in
--- a/src/prg/bash/wutconv.sh.in
+++ b/src/prg/bash/wutconv.sh.in
@@ -91,6 +91,7 @@
 #				Introduce more meaningful exit codes.	#
 #				Tidy up local and global variables.	#
 # 20/09/2019	MG	1.1.2	Correct help output.			#
+# 11/10/2019	MG	1.1.3	Move script_exit() before it is used.	#
 #									#
 #########################################################################
 
@@ -98,7 +99,7 @@
 ##################
 # Init variables #
 ##################
-readonly version=1.1.2				# Script version
+readonly version=1.1.3				# Script version
 readonly outputprefix="$(basename $0): "
 readonly packageversion=@pkgversion@		# Package version
 
@@ -143,6 +144,14 @@ output()
 	fi
 }
 
+# Standard function to tidy up and return exit code.
+# Parameters - 	$1 is the exit code.
+# No return value.
+script_exit()
+{
+	exit $1
+}
+
 # Standard function to test command error and exit if non-zero.
 # Parameters - 	$1 is the exit code, (normally $? from the preceeding command).
 # No return value.
@@ -151,14 +160,6 @@ std_cmd_err_handler()
 	if (( $1 )); then
 		script_exit $1
 	fi
-}
-
-# Standard function to tidy up and return exit code.
-# Parameters - 	$1 is the exit code.
-# No return value.
-script_exit()
-{
-	exit $1
 }
 
 # Standard trap exit function.
