Standardise error handler function
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/wutconv.sh.in b/src/prg/bash/wutconv.sh.in
--- a/src/prg/bash/wutconv.sh.in
+++ b/src/prg/bash/wutconv.sh.in
@@ -111,12 +111,13 @@ output()
 	fi
 }
 
-# Standard function to test command error ($1 is $?) and exit if non-zero
+# Standard function to test command error and exit if non-zero.
+# Parameters - 	$1 is the exit code, (normally $? from the preceeding command).
+# No return value.
 std_cmd_err_handler()
 {
-	if [ $1 != 0 ]; then
-		script_exit_code=$1
-		script_exit
+	if (( $1 )); then
+		script_exit $1
 	fi
 }
 
