Improve output function
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/wutconv.sh.in b/src/prg/bash/wutconv.sh.in
--- a/src/prg/bash/wutconv.sh.in
+++ b/src/prg/bash/wutconv.sh.in
@@ -95,15 +95,19 @@ Usage is $0 [OPTIONS] TextFileName TextFileName1 ...
 EOF
 }
 
-# Output $1 to stdout or stderr depending on $2
+# Standard function to emit messages depending on various parameters.
+# Parameters -	$1 What:-	The message to emit.
+#		$2 Where:-	stdout == 0
+#				stderr == 1
+# No return value.
 output()
 {
-	if [ $2 = 0 ]; then
-		if [ "$verbosity" = "-v" ]; then
-			echo "$outputprefix$1"
+	if (( !$2 )); then
+		if [[ $verbosity == "-v" ]]; then
+			printf "%s\n" "$1"
 		fi
 	else
-		echo "$outputprefix$1" 1>&2
+		printf "%s\n" "$1" 1>&2
 	fi
 }
 
